kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-admin
  namespace: poao
  labels:
    team: poao
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://poao-admin.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 50
  liveness:
    path: /internal/health/liveness
    initialDelay: 50
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    outbound:
      rules:
        - application: veilarboppfolging
          namespace: poao
        - application: veilarbarena
          namespace: pto
          cluster: dev-fss
        - application: veilarbdialog
          namespace: dab
        - application: poao-tilgang
          namespace: poao
        - application: veilarbportefolje
          namespace: obo
        - application: veilarbvedtaksstotte
          namespace: poao
        - application: pdl-pip-api
          namespace: pdl
          cluster: dev-fss

  env:
    - name: VEILARBVEDTAKSSTOTTE_ADMIN_API_URL
      value: http://veilarbvedtaksstotte.obo
    - name: VEILARBOPPFOLGING_ADMIN_API_URL
      value: http://veilarboppfolging.poao
    - name: VEILARBARENA_ADMIN_API_URL
      value: https://veilarbarena.intern.dev.nav.no
    - name: VEILARBDIALOG_ADMIN_API_URL
      value: http://veilarbdialog.dab
    - name: VEILARBPORTEFOLJE_ADMIN_API_URL
      value: http://veilarbportefolje.obo
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: PDLPIP_SCOPE
      value: api://dev-fss.pdl.pdl-pip-api/.default
    - name: PDLPIP_URL
      value: https://pdl-pip-api.dev-fss-pub.nais.io
