apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pto-admin
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-admin/pto-admin:{{version}}
  port: 8080
  ingresses:
    - https://app.adeo.no/pto-admin
  liveness:
    path: /pto-admin/internal/isAlive
    initialDelay: 10
  readiness:
    path: /pto-admin/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: CORS_DOMAIN
      value: "*"
    - name: CONTEXT_PATH
      value: /pto-admin