apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pto-admin
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-frontend/pto-frontend:43fdd666f3a803f284da73b51e248c91b2760a3d
  port: 8080
  ingresses:
    - https://pto-admin.dev.adeo.no
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: CORS_DOMAIN
      value: "*"
    - name: JSON_CONFIG
      value: >
        {
          "proxies": [
            { "from": "/pto-admin-api", "to": "https://pto-admin-api.dev.adeo.no", "preserveContextPath": false }
          ]
        }
