kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: poao-admin
  namespace: poao
  labels:
    team: poao
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://poao-admin.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 50
  liveness:
    path: /internal/health/liveness
    initialDelay: 50
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvpto-admin
        mountPath: /var/run/secrets/nais.io/service_user
  accessPolicy:
    outbound:
      rules:
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: veilarboppfolging
          namespace: poao
        - application: veilarbdialog
          namespace: dab
        - application: veilarbportefolje
          namespace: obo
        - application: poao-tilgang
          namespace: poao
        - application: azure-token-generator
          namespace: aura
          cluster: prod-gcp
      external:
        - host: veilarbarena.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  env:
    - name: VEILARBVEDTAKSSTOTTE_ADMIN_API_URL
      value: http://veilarbvedtaksstotte.obo
    - name: VEILARBVEDTAKSSTOTTE_ADMIN_API_SCOPE
      value: api://dev-gcp.obo.veilarbvedtaksstotte/.default
    - name: VEILARBOPPFOLGING_ADMIN_API_URL
      value: http://veilarboppfolging.poao
    - name: VEILARBOPPFOLGING_ADMIN_API_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default
    - name: VEILARBARENA_ADMIN_API_URL
      value: https://veilarbarena.dev-fss-pub.nais.io
    - name: VEILARBARENA_ADMIN_API_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: VEILARBDIALOG_ADMIN_API_URL
      value: http://veilarbdialog.dab
    - name: VEILARBDIALOG_ADMIN_API_SCOPE
      value: api://dev-gcp.dab.veilarbdialog/.default
    - name: VEILARBPORTEFOLJE_ADMIN_API_URL
      value: http://veilarbportefolje.obo
    - name: VEILARBPORTEFOLJE_ADMIN_API_SCOPE
      value: api://dev-gcp.obo.veilarbportefolje/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: PDL_API_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_API_URL
      value: https://pdl-api.dev-fss-pub.nais.io

