kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-admin
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://pto-admin.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 50
  liveness:
    path: /internal/health/liveness
    initialDelay: 50
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          - id: 6844decc-33c2-421f-b8e9-d1015f497174
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvpto-admin
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: VEILARBVEDTAKSSTOTTE_ADMIN_API_URL
      value: https://veilarbvedtaksstotte.nais.adeo.no
    - name: VEILARBOPPFOLGING_ADMIN_API_URL
      value: https://veilarboppfolging.intern.nav.no
    - name: VEILARBARENA_ADMIN_API_URL
      value: https://veilarbarena.intern.nav.no
    - name: VEILARBDIALOG_ADMIN_API_URL
      value: https://veilarbdialog.nais.adeo.no
    - name: VEILARBPORTEFOLJE_ADMIN_API_URL
      value: https://veilarbportefolje-gcp.intern.nav.no
    - name: POAO_TILGANG_URL
      value: https://poao-tilgang.intern.nav.no
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
  envFrom:
    - configmap: pto-config
