kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-admin
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-admin/pto-admin:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://pto-admin.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvpto-admin
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: VEILARBVEDTAKSSTOTTE_ADMIN_API_URL
      value: https://app-q1.adeo.no/veilarbvedtaksstotte/api/admin
  envFrom:
    - configmap: pto-config
    - secret: pto-admin
