kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-admin
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/pto-admin/pto-admin:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://pto-admin.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvpto-admin
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: VEILARBVEDTAKSSTOTTE_ADMIN_API_URL
      value: https://veilarbvedtaksstotte-q1.nais.preprod.local
    - name: VEILARBOPPFOLGING_ADMIN_API_URL
      value: https://veilarboppfolging.dev.intern.nav.no
    - name: VEILARBARENA_ADMIN_API_URL
      value: https://veilarbarena.dev.intern.nav.no
    - name: VEILARBDIALOG_ADMIN_API_URL
      value: https://veilarbdialog-q1.nais.preprod.local
    - name: VEILARBPORTEFOLJE_ADMIN_API_URL
      value: https://veilarbportefolje.dev.intern.nav.no
    - name: POAO_TILGANG_URL
      value: https://poao-tilgang.dev.intern.nav.no
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
  envFrom:
    - configmap: pto-config
