management:
  endpoints:
    web:
      base-path: /internal
      exposure:
        include: prometheus,health
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      default-filters:
        - RewritePath=(/api/admin)(/[a-z\d]+)(.*), $\2$\1$\3
        - RemoveRequestHeader=Cookie
      routes:
        - id: veilarbvedtaksstotte
          uri: ${VEILARBVEDTAKSSTOTTE_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarbvedtaksstotte/**
        - id: veilarboppfolging
          uri: ${VEILARBOPPFOLGING_ADMIN_API_URL}
          predicates:
            - Path=/api/veilarboppfolging/**
          filters:
            - RewritePath=/api/veilarboppfolging/(?<remainingPath>.*), /${remainingPath}
        - id: veilarbarena
          uri: ${VEILARBARENA_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarbarena/**
        - id: veilarbdialog
          uri: ${VEILARBDIALOG_ADMIN_API_URL}
          predicates:
            - Path=/api/veilarbdialog/**
          filters:
            - RewritePath=/api/veilarbdialog/(?<remainingPath>.*), /${remainingPath}
        - id: veilarbaktivitet
          uri: ${VEILARBAKTIVITET_ADMIN_API_URL}
          predicates:
            - Path=/api/veilarbaktivitet/**
          filters:
            - RewritePath=/api/veilarbaktivitet/(?<remainingPath>.*), /${remainingPath}
        - id: veilarbportefolje
          uri: ${VEILARBPORTEFOLJE_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarbportefolje/**
        - id: ao-oppfolgingskontor
          uri: ${AO_OPPFOLGINGSKONTOR_API_URL}
          predicates:
            - Path=/api/ao-oppfolgingskontor/**
          filters:
            - RewritePath=/api/ao-oppfolgingskontor/(?<remainingPath>.*), /${remainingPath}

app:
  env:
    allowedAdminUsers: ${ALLOWED_ADMIN_USERS}
    poaoTilgangUrl: ${POAO_TILGANG_URL:#{null}}
    poaoTilgangScope: ${POAO_TILGANG_SCOPE:#{null}}
    naisAadDiscoveryUrl: ${AZURE_APP_WELL_KNOWN_URL}
    naisAadClientId: ${AZURE_APP_CLIENT_ID}
    pdlpipUrl: ${PDLPIP_URL}
    pdlpipScope: ${PDLPIP_SCOPE}
