management:
  endpoints:
    web:
      base-path: /internal
      exposure:
        include: prometheus,health
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          azure:
            client-name: PTO Admin
            client-id: ${AZURE_APP_CLIENT_ID:}
            client-secret: ${AZURE_APP_CLIENT_SECRET:}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/oauth2/callback'
            scope: openid, profile
        provider:
          azure:
            issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER:}
            jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI:}
  cloud:
    gateway:
      default-filters:
        - RewritePath=(/api/admin)(/[a-z\d]+)(.*), $\2$\1$\3
        - RemoveRequestHeader=Cookie
      routes:
        - id: veilarbvedtaksstotte
          uri: ${VEILARBVEDTAKSSTOTTE_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarbvedtaksstotte/**
        - id: veilarboppfolging
          uri: ${VEILARBOPPFOLGING_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarboppfolging/**
        - id: veilarbarena
          uri: ${VEILARBARENA_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarbarena/**
        - id: veilarbdialog
          uri: ${VEILARBDIALOG_ADMIN_API_URL}
          predicates:
            - Path=/api/admin/veilarbdialog/**

app:
  env:
    stsDiscoveryUrl: ${SECURITY_TOKEN_SERVICE_DISCOVERY_URL}
    openAmDiscoveryUrl: ${OPENAM_DISCOVERY_URL}
    veilarbloginOpenAmClientId: ${VEILARBLOGIN_OPENAM_CLIENT_ID}
    abacUrl: ${ABAC_PDP_ENDPOINT_URL}
    allowedAdminUsers: ${ALLOWED_ADMIN_USERS}
    onPremKafkaBrokersUrl: ${KAFKA_BROKERS_URL}

