package no.nav.pto_admin.utils

enum class AppName {
    VEILARBPORTEFOLJE,
    VEILARBVEDTAKSTOTTE,
    VEILARBOPPFOLGING,
    VEILARBARENA,
    VEILARBDIALOG,
    VEILARBAKTIVITET,
    AO_OPPFOLGINGSKONTOR
}
