package no.nav.pto_admin.utils

enum class SystembrukereAzure {
    VEILARBPORTEFOLJE,
    VEILARBVEDTAKSTOTTE,
    VEILARBOPPFOLGING,
    VEILARBDIALOG,
    VEILARBAKTIVITET,
    AO_OPPFOLGINGSKONTOR
}
