/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://github-package-registry-mirror.gc.nav.no/cached/maven-release")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(libs.org.springframework.boot.spring.boot.starter.cache)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.springframework.boot.spring.boot.starter.logging)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.client)
    api(libs.org.springframework.cloud.spring.cloud.starter.gateway)
    api(libs.no.nav.poao.tilgang.client)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    api(libs.com.github.ben.manes.caffeine.caffeine)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    api(libs.no.nav.common.log)
    api(libs.no.nav.common.util)
    api(libs.no.nav.common.types)
    api(libs.no.nav.common.client)
    api(libs.no.nav.common.token.client)
    api(libs.no.nav.common.auth)
    api(libs.no.nav.common.health)
    api(libs.no.nav.common.kafka)
    api(libs.com.squareup.okhttp3.okhttp)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    testImplementation(libs.org.springframework.security.spring.security.test)
    testImplementation(libs.no.nav.security.mock.oauth2.server)
    testImplementation(libs.org.mockito.kotlin.mockito.kotlin)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.com.squareup.okhttp3.mockwebserver)
}

group = "no.nav.pto-admin"
version = "1.0.0"
description = "pto-admin"
java.sourceCompatibility = JavaVersion.VERSION_23

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.register<Copy>("moveFrontendAssets") {
    from(file("web-app/build"))
    into(file("api/src/main/resources/public"))
}

tasks.named("build") {
    dependsOn("moveFrontendAssets")
}