/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.0.20"
    kotlin("plugin.spring") version "2.1.20-RC2"
    id("org.springframework.boot") version "3.4.3"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://github-package-registry-mirror.gc.nav.no/cached/maven-release")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter.webflux)
    implementation(libs.org.springframework.boot.spring.boot.starter.cache)
    implementation(libs.org.springframework.boot.spring.boot.starter.actuator)
    implementation(libs.org.springframework.boot.spring.boot.starter.logging)
    implementation(libs.org.springframework.cloud.spring.cloud.starter.gateway)
    implementation(libs.no.nav.poao.tilgang.client)
    implementation(libs.org.jetbrains.kotlin.kotlin.reflect)
    implementation(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    implementation(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    implementation(libs.com.github.ben.manes.caffeine.caffeine)
    implementation(libs.io.micrometer.micrometer.registry.prometheus)
    implementation(libs.no.nav.common.log)
    implementation(libs.no.nav.common.util)
    implementation(libs.no.nav.common.types)
    implementation(libs.no.nav.common.client)
    implementation(libs.no.nav.common.token.client)
    implementation(libs.no.nav.common.auth)
    implementation(libs.no.nav.common.health)
    implementation(libs.no.nav.common.kafka)
    implementation(libs.com.squareup.okhttp3.okhttp)
    implementation(libs.org.springframework.boot.spring.boot.configuration.processor)

    testImplementation(libs.org.springframework.boot.spring.boot.starter.oauth2.client)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.security)
    testImplementation(libs.org.springframework.security.spring.security.test)
    testImplementation(libs.no.nav.security.mock.oauth2.server)
    testImplementation(libs.org.mockito.kotlin.mockito.kotlin)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.com.squareup.okhttp3.mockwebserver)
    testRuntimeOnly(libs.org.junit.platform.junit.platform.launcher)
}

group = "no.nav.pto-admin"
version = "1.0.0"
description = "pto-admin"
java.sourceCompatibility = JavaVersion.VERSION_21
