name: Deploy to dev
run-name: Deploy ${{ github.ref_name }} to dev by ${{ github.actor }}
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/${{ github.repository }}/pto-admin
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # ratchet:actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # ratchet:gradle/actions/setup-gradle@v6
        with:
          gradle-version: "8.13"
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/gradle' }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache_dependency_path: web-app/pnpm-lock.yaml
          cache: true
          version: 11

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: web-app/pnpm-lock.yaml
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        working-directory: web-app
        run: pnpm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build frontend assets
        working-directory: web-app
        run: pnpm run build

      - name: Move frontend assets to public folder
        run: mv ./web-app/build ./api/src/main/resources/public

      - name: Build gradle
        run: ./gradlew build

      - name: Build and push Docker image
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: poao

  deploy-dev:
    name: Deploy application to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v6

      - name: Deploy application
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
