name: Deploy to dev
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/${{ github.repository }}/pto-admin
  PRINT_PAYLOAD: true
permissions:
  packages: write
  
jobs:
  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13"
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/gradle' }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web-app/package-lock.json
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci --prefix web-app --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build frontend assets
        run: npm run build --prefix web-app

      - name: Move frontend assets to public folder
        run: mv ./web-app/build ./api/src/main/resources/public

      - name: Build gradle
        run: ./gradlew build

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pto
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy application to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
