name: Deploy to dev
run-name: Deploy ${{ github.ref_name }} to dev by ${{ github.actor }}
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/${{ github.repository }}/pto-admin
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - name: Set up Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # ratchet:actions/setup-java@v6.0.1
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # ratchet:gradle/actions/setup-gradle@v6
        with:
          gradle-version: "8.13"
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/gradle' }}

      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # ratchet:pnpm/action-setup@v6.1.0
        with:
          cache_dependency_path: web-app/pnpm-lock.yaml
          cache: true
          version: 11

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: web-app/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: web-app
        run: pnpm ci

      - name: Build frontend assets
        working-directory: web-app
        run: pnpm run build

      - name: Move frontend assets to public folder
        run: mv ./web-app/build ./api/src/main/resources/public

      - name: Build gradle
        run: ./gradlew build

      - name: Build and push Docker image
        uses: nais/docker-build-push@0e73849f69ff260ee27597553c0a7848ca4e9795 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: poao

  deploy-dev:
    name: Deploy application to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - name: Deploy application
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
